/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLogoutRouteImport } from './routes/api/public/logout'
import { Route as ApiPublicSendTelegramRouteImport } from './routes/api/public/send-telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogoutRoute = ApiPublicLogoutRouteImport.update({
  id: '/api/public/logout',
  path: '/api/public/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendTelegramRoute = ApiPublicSendTelegramRouteImport.update({
  id: '/api/public/send-telegram',
  path: '/api/public/send-telegram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/logout': typeof ApiPublicLogoutRoute
  '/api/public/send-telegram': typeof ApiPublicSendTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/logout': typeof ApiPublicLogoutRoute
  '/api/public/send-telegram': typeof ApiPublicSendTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/logout': typeof ApiPublicLogoutRoute
  '/api/public/send-telegram': typeof ApiPublicSendTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/logout' | '/api/public/send-telegram'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/logout' | '/api/public/send-telegram'
  id: '__root__' | '/' | '/api/public/logout' | '/api/public/send-telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicLogoutRoute: typeof ApiPublicLogoutRoute
  ApiPublicSendTelegramRoute: typeof ApiPublicSendTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/logout': {
      id: '/api/public/logout'
      path: '/api/public/logout'
      fullPath: '/api/public/logout'
      preLoaderRoute: typeof ApiPublicLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-telegram': {
      id: '/api/public/send-telegram'
      path: '/api/public/send-telegram'
      fullPath: '/api/public/send-telegram'
      preLoaderRoute: typeof ApiPublicSendTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicLogoutRoute: ApiPublicLogoutRoute,
  ApiPublicSendTelegramRoute: ApiPublicSendTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
